### ISSUE TITLE
Running tests failed

### ISSUE THREAD

**Issue by squattertim** [eugene-kamenev/gorm-orientdb#1]
Hello Eugene,
I like this project! I've downloaded, run `gradle` and then I tried to run `gradle test` and all tests failed with following reasons:
- `java.lang.IllegalStateException at AttachMethodSpec.groovy`, etc.
- `org.spockframework.runtime.WrongExceptionThrownError at OrientDbCrudOperationsSpec.groovy:68`, etc.
- `java.io.FileNotFoundException at MainIntegrationTest.groovy`

Is there any chance I'm doing something wrong?
Best regards,
Tomas

**Comment by eugene-kamenev** [comment]
As I remember, you could run OrientDbSuite.groovy, if you decide to change
tests to graph/document take a look at Setup.groovy.
Sorry far away from my workplace now.
Hope it helps.

**Comment by squattertim** [comment]
Hello Eugene,
thanks a lot for Your suggestions. I'm fighting hard with running tests, but without any success up to now. When I tried to run the `OrientDbSuite`, I ended up with `Empty test suite`.
Tomas

**Comment by squattertim** [comment]
Even when I run Gradle task `test` in IJ, all tests fail with an `IllegalStateException` like this:

`Either class [grails.gorm.tests.Person] is not a domain class or GORM has not been initialized correctly or has already been shutdown. Ensure GORM is loaded and configured correctly before calling any methods on a GORM entity.`

Could You please checkout the project into some "clean" environment and try to build it and run test, so maybe You'll see what is happening there? I'd also thought about project dependencies, I mean whether there are some projects, like `grails-datastore-gorm-orient` I should add?

**Comment by eugene-kamenev** [comment]
Ok, now take a look at Setup.groovy and uncomment string with GORM Person
class declaration. Sorry for this.

20 авг. 2016 г. 6:05 PM пользователь "squattertim" notifications@github.com
написал:

**Comment by eugene-kamenev** [comment]
Oh, give me a moment. I have clean environment right now, will take a look
into it.

20 авг. 2016 г. 6:55 PM пользователь "Eugene Kamenev" <
eugene.kamenev@gmail.com> написал:

**Comment by squattertim** [comment]
Thanks a lot, Eugene!

**Comment by eugene-kamenev** [comment]
Ok, my environment is:
1. Gradle 2.13
2. Java 1.7
3. IntelliJ IDEA 15 Community Edition (at work I am using 2016)

Cloned the project, build the project with IDEA. Created run configuration for OrientDbSuite.groovy.

Testing report:
OrientDbSuite: 130 total, 5 failed, 8 ignored, 117 passed

So 5 tests that failed seems to be ok, it the current stage of the project.

Let me tell you something more, if you like to change tests from graph (as it is configured right now) and use document tests, then you must just change `import grails.gorm.tests.orientdb.graph.*` to `import grails.gorm.tests.orientdb.document.*` at OrientDbSuite.groovy file. And then change also package for entities that are used in tests. Change `import org.grails.datastore.gorm.orient.entity.graph.*` to `import org.grails.datastore.gorm.orient.entity.document.*` at Setup.groovy. 
If you want to run MixedRelationships tests, take a look Setup.groovy and uncomment additional entities.

Hope it helps. Let me know if you still experience troubles.

**Comment by eugene-kamenev** [comment]
> Even when I run Gradle task test

Do not run gradle test task, create run configuration for OrientDbSuite.groovy.
Now it is clear :)

**Comment by squattertim** [comment]
What version of Groovy SDK are You using?

**Comment by squattertim** [comment]
Hello Eugene,
my environment is:
- Gradle 2.14
- Java 1.7
- IntelliJ IDEA 16.2.2

I have followed Your instructions, but the result is now:

`Class not found: "grails.gorm.tests.orientdb.graph.OrientDbCrudOperationsSpec"Empty test suite.`

Have You specified some particular environment for running OrientDbSuite?

**Comment by squattertim** [comment]
I'm also importing the project as Gradle project, because otherwise I'm without dependencies.

**Comment by squattertim** [comment]
.. and now it finally works.. = )

**Comment by squattertim** [comment]
I have to find some bottle of Champagne! =D

**Comment by squattertim** [comment]
Thanks for Your help, Eugene! I'm not particularly sure what finally helped, cause I tried so many combinations and I need to repeat them tomorrow to be sure, which one worked.. = ) I'll write it down here then. But now I would rather look more into the code itself..

**Comment by squattertim** [comment]
It turned out, that it depends on whether You just simply import the project into IntelliJ Idea and then convert it to Gradle project, or if You directly import the project as a Gradle project..

**Comment by eugene-kamenev** [comment]
Keep me posted how it goes. I am interested to finish this implementation,
but need somebody to help me and motivate a little.

2016-08-22 3:47 GMT+06:00 squattertim notifications@github.com:
